/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  


        ADD_FAV("[save][]",1500),
        OPEN_FAV("[open][fav]",1500),
        GO_BACK("[goBack]",1500),
        PREVIOUS_TAB("[previous][tab]",1500),
        CLOSE_TAB("[close]",1500),
        QUANTITY_TOTAL("[total]",1500),
        NEXT_TAB("[next][tab]",1500),

    
        OPEN_TAB("[open][tab]",1500),
        OPEN_HISTORIC("[open][historic]",1500),
        ZOOM_IN("[zoom_in]",1500),
        SCROLL_UP("[scroll_up]",1500),
        SCROLL_DOWN("[scroll_down]",1500),
        ZOOM_OUT("[zoom_out]",1500),
        MINIMIZE("[minimize]",1500),
        MAXIMIZE("[maximize]",1500),
        TIMES_2("[2x]",2500),
        TIMES_3("[3x]",2500),
        TIMES_TOTAL("[100x]",2500);
        
        
private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
