/* 
  *   Speech.java generated by speechmod 
 */   

package scxmlgen.Modalities; 

import scxmlgen.interfaces.IModality; 

public enum Speech implements IModality{  

    
        OPEN_TAB("[open][tab]",1500),
        OPEN_HISTORIC("[open][historic]",1500),
        OPEN_LINK("[open][]",1500),
        ADD_FAV("[save][fav]",1500),
        OPEN_FAV("[open][fav]",1500),
	SEARCH("[search][]",1500),
        ZOOM_IN("[zoom_in][]",1500),
        ZOOM_OUT("[zoom_out][]",1500),
        GO_BACK("[goBack][]",1500),
        MINIMIZE("[minimize]",1500),
        MAXIMIZE("[maximize]",1500),
        PREVIOUS_TAB("[previous][]",1500),
        CLOSE_TAB("[close][tab]",1500),
        QUANTITY_TIMES("[]",1500),
        QUANTITY_TOTAL("[total]",1500),
        NEXT_TAB("[next][]",1500);
        
        
private String event; 
private int timeout;
Speech(String m, int time) {
	event=m;
	timeout=time;
}
@Override
public int getTimeOut(){
	return timeout;
}
@Override
public String getEventName(){
	return event;
}
@Override
public String getEvName(){
	return getModalityName().toLowerCase() +event.toLowerCase();
}

}
